# Generated by Django 4.1.2 on 2023-08-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0002_alter_token_asset"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CambioEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cadete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.cadete",
                    ),
                ),
                (
                    "cambio_estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pedidos.cambioestado",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="productos.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="productos.ingrediente",
                    ),
                ),
                (
                    "item_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pedidos.itempedido",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cambioestado",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="pedidos.estado"
            ),
        ),
    ]
