# Generated by Django 4.1.2 on 2023-08-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_alter_token_asset"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="cambio_estado",
        ),
        migrations.AddField(
            model_name="cambioestado",
            name="pedido",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                to="pedidos.pedido",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cadete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="usuarios.cadete",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="usuarios.cliente",
            ),
        ),
    ]
