# Generated by Django 4.1.2 on 2023-08-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0002_remove_pedido_cambio_estado_cambioestado_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="pedidos.pedido",
            ),
        ),
    ]
