# Generated by Django 4.1.2 on 2023-08-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0004_detalleitem_cantidad_alter_detalleitem_item_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleitem",
            name="item_pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="pedidos.itempedido",
            ),
        ),
    ]
