# Generated by Django 4.1.2 on 2023-08-21 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0005_alter_detalleitem_item_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambioestado",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="cambios",
                to="pedidos.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="estado",
            name="nombre",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
