# Generated by Django 4.1.2 on 2023-09-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0018_alter_cliente_domicilio"),
        ("main", "0001_initial"),
        ("pedidos", "0006_alter_cambioestado_pedido_alter_estado_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambioestado",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="main.estado"
            ),
        ),
        migrations.AlterField(
            model_name="cambioestado",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="cambios_estado",
                to="pedidos.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pedidos",
                to="usuarios.cliente",
            ),
        ),
        migrations.DeleteModel(
            name="Estado",
        ),
    ]
