# Generated by Django 4.1.2 on 2023-09-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "pedidos",
            "0007_alter_cambioestado_estado_alter_cambioestado_pedido_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambioestado",
            name="fecha_hora",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cambioestado",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cambios_estado",
                to="pedidos.pedido",
            ),
        ),
    ]
