# Generated by Django 4.1.2 on 2023-09-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0009_alter_categoria_imagen_alter_producto_descripcion"),
        ("pedidos", "0008_alter_cambioestado_fecha_hora_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productos.producto"
            ),
        ),
    ]
