# Generated by Django 4.1.2 on 2023-08-17 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localidad", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 8, 18, 0, 30, 15, 237725)
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="usuarios.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=40)),
                ("numero", models.PositiveSmallIntegerField()),
                ("torre", models.PositiveBigIntegerField()),
                ("departamento", models.CharField(max_length=10)),
                ("piso", models.PositiveSmallIntegerField()),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.localidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="usuarios.user",
                    ),
                ),
                ("dni", models.PositiveIntegerField()),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("mail", models.EmailField(max_length=254)),
                ("telefono", models.PositiveBigIntegerField()),
                ("nacimiento", models.DateField()),
                (
                    "domicilio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.domicilio",
                    ),
                ),
            ],
            bases=("usuarios.user",),
        ),
    ]
