# Generated by Django 4.1.2 on 2023-08-18 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_alter_token_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="asset",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 19, 18, 33, 17, 569717)
            ),
        ),
    ]
