# Generated by Django 4.1.2 on 2023-08-19 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0009_alter_token_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="asset",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 20, 22, 45, 6, 830997)
            ),
        ),
    ]
