# Generated by Django 4.1.2 on 2023-08-21 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0012_alter_token_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("torre", models.PositiveBigIntegerField()),
                ("departamento", models.CharField(max_length=10)),
                ("piso", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="domicilio",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="domicilio",
            name="piso",
        ),
        migrations.RemoveField(
            model_name="domicilio",
            name="torre",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="apellido",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dni",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="asset",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 22, 23, 33, 38, 49274)
            ),
        ),
        migrations.AddField(
            model_name="domicilio",
            name="edificio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.departamento",
            ),
            preserve_default=False,
        ),
    ]
