# Generated by Django 4.1.2 on 2023-08-21 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0013_departamento_remove_domicilio_departamento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departamento",
            old_name="departamento",
            new_name="codigo",
        ),
        migrations.AlterField(
            model_name="domicilio",
            name="edificio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="asset",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 22, 23, 36, 34, 608677)
            ),
        ),
    ]
