# Generated by Django 4.1.2 on 2023-08-21 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0014_rename_departamento_departamento_codigo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="user_ptr",
        ),
        migrations.AddField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="usuarios.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="token",
            name="asset",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 22, 23, 44, 54, 559256)
            ),
        ),
    ]
