# Generated by Django 4.1.2 on 2023-09-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0016_remove_cliente_user_cliente_user_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="token",
            name="asset",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="user_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="usuarios.user",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token",
                to="usuarios.user",
            ),
        ),
    ]
