# Generated by Django 4.1.2 on 2023-09-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0017_remove_cliente_dni_remove_token_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="domicilio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="usuarios.domicilio",
            ),
        ),
    ]
