# Generated by Django 4.1.2 on 2023-08-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("imagen", models.ImageField(upload_to="")),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tamaño", models.CharField(max_length=40)),
                ("precio", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("precio", models.PositiveSmallIntegerField()),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("imagen", models.ImageField(upload_to="")),
                ("descripcion", models.TextField()),
                ("stock", models.PositiveSmallIntegerField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "categorias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="productos.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField()),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="productos.ingrediente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="productos.producto",
                    ),
                ),
            ],
        ),
    ]
