# Generated by Django 4.1.2 on 2023-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(upload_to="productos/static"),
        ),
    ]
