# Generated by Django 4.1.2 on 2023-08-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0004_rename_categorias_producto_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleproducto",
            name="produco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="detalles",
                to="productos.producto",
            ),
            preserve_default=False,
        ),
    ]
