# Generated by Django 4.1.2 on 2023-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0005_detalleproducto_produco"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DetalleProducto",
        ),
    ]
