# Generated by Django 4.1.2 on 2023-08-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0006_producto_precio_delete_detalleproducto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalleingrediente",
            name="cantidad",
        ),
        migrations.AlterField(
            model_name="detalleingrediente",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="detalles",
                to="productos.producto",
            ),
        ),
    ]
