# Generated by Django 4.1.2 on 2023-09-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0007_remove_detalleingrediente_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="productos",
                to="productos.categoria",
            ),
        ),
    ]
