# Generated by Django 4.1.2 on 2023-09-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0008_alter_producto_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos/static/categorias"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
