# Generated by Django 4.1.2 on 2023-09-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0009_alter_categoria_imagen_alter_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now=True)),
                ("hora", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VarianteProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ItemCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.PositiveSmallIntegerField()),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="productos.catalogo",
                    ),
                ),
                (
                    "productos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="productos.producto",
                    ),
                ),
            ],
        ),
    ]
